export const weatherAnimations = {
  "Partly cloudy": require("../assets/animations/partlycloudyy.json"),
  "Moderate rain": require("../assets/animations/heavyrain.json"),
  "Patchy rain possible": require("../assets/animations/rain.json"),
  'Sunny': require("../assets/animations/sun2.json"),
  'Clear': require("../assets/animations/clear.json"),
  'Overcast': require("../assets/animations/clouds.json"),
  'Cloudy': require("../assets/animations/clouds.json"),
  "Light rain": require("../assets/animations/heavyrain.json"),
  "Moderate rain at times": require("../assets/animations/heavyrain.json"),
  "Heavy rain": require("../assets/animations/heavyrain.json"),
  "Heavy rain at times": require("../assets/animations/heavyrain.json"),
  "Moderate or heavy freezing rain": require("../assets/animations/heavyrain.json"),
  "Moderate or heavy rain shower": require("../assets/animations/heavyrain.json"),
  "Moderate or heavy rain with thunder": require("../assets/animations/heavyrain.json"),
  'Mist': require("../assets/animations/clouds.json"),
  'Fog': require("../assets/animations/clouds.json"),
  'other': require("../assets/animations/rain.json"),
};
