export const weatherImagesbg = {
  "Partly cloudy": require("../assets/images/partlycloudy.jpg"),
  "Moderate rain": require("../assets/images/moderaterain.jpg"),
  "Patchy rain possible": require("../assets/images/moderaterain.jpg"),
  'Sunny': require("../assets/images/sun.jpg"),
  'Clear': require("../assets/images/clear.jpg"),
  'Overcast': require("../assets/images/clouds.jpg"),
  'Cloudy': require("../assets/images/clouds.jpg"),
  "Light rain": require("../assets/images/moderaterain.jpg"),
  "Moderate rain at times": require("../assets/images/moderaterain.jpg"),
  "Heavy rain": require("../assets/images/rainy.jpg"),
  "Heavy rain at times": require("../assets/images/rainy.jpg"),
  "Moderate or heavy freezing rain": require("../assets/images/rainy.jpg"),
  "Moderate or heavy rain shower": require("../assets/images/rainy.jpg"),
  "Moderate or heavy rain with thunder": require("../assets/images/rainy.jpg"),
  'Mist': require("../assets/images/mist.jpg"),
  "Fog": require("../assets/images/mist.jpg"),
  'other': require("../assets/images/moderaterain.jpg"),
};
